const ENV_ID = "cloud1-d3g17rpe7566d3d5c";

const CLOUDBASE_ENABLED = true;
const CLOUDBASE_HOSTING_ENABLED = true;
const CLOUDBASE_HOSTING_READY = true;
const CLOUDBASE_HOSTING_BASE_URL = "https://cloud1-d3g17rpe7566d3d5c-1442900641.tcloudbaseapp.com";
const CLOUDBASE_AI_ENABLED = true;
const CLOUDBASE_AI_MODEL = "hy3-preview";
const CLOUDBASE_AI_PROMO_EXPIRES_AT = "2026-12-14T23:59:59+08:00";

const AI_GENERATIVE_PUBLIC_ENABLED = false;
const AI_COMPETITION_MODE = false;
const AI_TOOL_ONLY_MODE = false;
const AI_CLIENT_EXPRESSION_LAYER_ENABLED = false;
const AI_MAX_HISTORY_MESSAGES = 6;
const AI_MAX_USER_MESSAGE_LENGTH = 1200;
const AI_MAX_DAILY_GENERATIVE_REQUESTS = 20;
const AI_VOICE_INPUT_ENABLED = false;
const AI_VOICE_PROVIDER = "";
const AI_VOICE_MAX_DURATION_MS = 15000;
const AI_VOICE_DAILY_LIMIT = 30;

module.exports = {
  ENV_ID,
  CLOUDBASE_ENABLED,
  CLOUDBASE_HOSTING_ENABLED,
  CLOUDBASE_HOSTING_READY,
  CLOUDBASE_HOSTING_BASE_URL,
  CLOUDBASE_AI_ENABLED,
  CLOUDBASE_AI_MODEL,
  CLOUDBASE_AI_PROMO_EXPIRES_AT,
  AI_GENERATIVE_PUBLIC_ENABLED,
  AI_COMPETITION_MODE,
  AI_TOOL_ONLY_MODE,
  AI_CLIENT_EXPRESSION_LAYER_ENABLED,
  AI_MAX_HISTORY_MESSAGES,
  AI_MAX_USER_MESSAGE_LENGTH,
  AI_MAX_DAILY_GENERATIVE_REQUESTS,
  AI_VOICE_INPUT_ENABLED,
  AI_VOICE_PROVIDER,
  AI_VOICE_MAX_DURATION_MS,
  AI_VOICE_DAILY_LIMIT,
};
