param(
    [string]$PptxPath = (Join-Path $PSScriptRoot "..\校园智序-小序-答辩.pptx")
)

$ErrorActionPreference = "Stop"

$resolved = (Resolve-Path -LiteralPath $PptxPath).Path
$powerPoint = $null
$presentation = $null

# PowerPoint / Office animation enum values.  Using numeric constants keeps the
# script independent of a locally installed Office interop assembly.
$msoAnimEffectFade = 10
$msoAnimTriggerOnPageClick = 1
$msoAnimTriggerWithPrevious = 2

try {
    $powerPoint = New-Object -ComObject PowerPoint.Application
    $powerPoint.Visible = -1
    $presentation = $powerPoint.Presentations.Open($resolved, $false, $false, $false)

    $audit = @()
    foreach ($slide in $presentation.Slides) {
        $sequence = $slide.TimeLine.MainSequence

        # Idempotency: remove effects generated by an earlier invocation.
        for ($i = $sequence.Count; $i -ge 1; $i--) {
            $sequence.Item($i).Delete()
        }

        $groups = @{}
        foreach ($shape in $slide.Shapes) {
            if ($shape.Name -match '^A(?<group>\d{2})_') {
                $groupId = [int]$Matches['group']
                if (-not $groups.ContainsKey($groupId)) {
                    $groups[$groupId] = @()
                }
                $groups[$groupId] += $shape
            }
        }

        $effectCount = 0
        foreach ($groupId in ($groups.Keys | Sort-Object)) {
            $isFirst = $true
            foreach ($shape in ($groups[$groupId] | Sort-Object Name)) {
                $trigger = if ($isFirst) { $msoAnimTriggerOnPageClick } else { $msoAnimTriggerWithPrevious }
                $effect = $sequence.AddEffect($shape, $msoAnimEffectFade, 0, $trigger)
                $effect.Timing.Duration = 0.38
                $effectCount++
                $isFirst = $false
            }
        }

        $audit += [pscustomobject]@{
            Slide = $slide.SlideIndex
            ClickGroups = $groups.Count
            Effects = $effectCount
        }
    }

    $presentation.Save()
    $audit | Format-Table -AutoSize

    if (($audit | Where-Object { $_.ClickGroups -lt 2 -or $_.Effects -lt 2 }).Count -gt 0) {
        throw "Animation validation failed: every slide must contain at least two click groups and two effects."
    }
}
finally {
    if ($null -ne $presentation) {
        $presentation.Close()
        [void][Runtime.InteropServices.Marshal]::ReleaseComObject($presentation)
    }
    if ($null -ne $powerPoint) {
        $powerPoint.Quit()
        [void][Runtime.InteropServices.Marshal]::ReleaseComObject($powerPoint)
    }
    [GC]::Collect()
    [GC]::WaitForPendingFinalizers()
}
